Repository postcss/postcss-loader, pull requests merged in 2018-08, with the labels that each got.

#378 docs(README): update extract CSS example
  README.md
Labels: scope: webpack, semver: patch, status: approved, type: docs

#382 ci(package): run tests in an explicit environment (`jest --env=node`)
  package.json
Labels: semver: patch, status: approved, type: ci

#381 ci(appveyor): readd Appveyor CI
  appveyor.yml
Labels: pr: review, priority: high, semver: patch, status: pending, type: ci

#380 docs(README): add autoprefixing example
  README.md
Labels: scope: postcss, semver: patch, status: approved, type: docs
