Repository postcss/postcss-loader, pull requests merged in 2018-07, with the labels that each got.

#370 fix(package): config memory leak(s)
  lib/index.js
  package.json
Labels: semver: patch, status: approved, type: bug

#371 docs(README): clarify `path` option description (`options.config.path`)
  README.md
Labels: scope: postcss-load-config, semver: patch, status: approved, type: docs

#377 docs(README): resolve http redirects and use https
  README.md
Labels: semver: patch, status: approved, type: docs
